### ISSUE TITLE
Streamline log files as SF now does

### ISSUE THREAD

**Issue by Toflar** [contao/standard-edition#32]
See http://symfony.com/blog/new-in-symfony-streamlined-log-files

**Comment by leofeyer** [comment]
We might as well change this in version 4.1.1, don't you think?

**Comment by Toflar** [comment]
I think, yes.

**Comment by leofeyer** [comment]
The following configuration works best for me:

``` yml
monolog:
    handlers:
        main:
            type:      rotating_file
            max_files: 10
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            level:     debug
            channels:  [!doctrine, !event, !php]
```

Since we are still using scopes, the log file was cluttered with deprecation warnings, which is why I have added `!php`.
