### ISSUE TITLE
Add basic security

### ISSUE THREAD

**Issue by leofeyer** [contao/standard-edition#54]
I would like to add the [NelmioSecurityBundle](https://github.com/nelmio/NelmioSecurityBundle) to our default configuration and configure it with the following basic settings:

```yaml
# Security configuration
nelmio_security:
    clickjacking:
        paths:
            '^/.*': SAMEORIGIN
    content_type:
        nosniff: true
    referrer_policy:
        enabled: true
        policies:
            - 'origin-when-cross-origin'
    xss_protection:
        enabled: true
        mode_block: true
```

These basic settings should apply (and should be applied :smile:) to every website.

@contao/developers Any objections?

**Comment by aschempp** [comment]
Can you quickly sum up what this does?

**Comment by leofeyer** [comment]
It adds some security headers as e.g. described here:

https://scotthelme.co.uk/hardening-your-http-response-headers/

* `X-Frame-Options "SAMEORIGIN"`
* `X-Content-Type-Options "nosniff"`
* `Referrer-Policy "origin-when-cross-origin"`
* `X-Xss-Protection "1; mode=block"`

You can then check your website on securityheaders.io, e.g.:

https://securityheaders.io/?q=https%3A%2F%2Fhostingwerk.de&followRedirects=on

**Comment by Toflar** [comment]
Yes please! That was somewhere on my list too :) Did you check whether we could use CSP to? We're adding stuff via the `$GLOBALS['TL_JAVASCRIPT']` etc. dynamically anyway so maybe we could also add nonces etc. This would greatly enhance Contao's security out-of-the-box :)

**Comment by leofeyer** [comment]
CSP is a lot more complex to implement and probably something that needs to be configured individually. The biggest hurdle are the lots of inline scripts IMO, which we add not only via `$GLOBALS['TL_JAVASCRIPT']` but also directly in many of the templates.

Therefore this PR only focuses on the basic changes that are implemented quickly.

**Comment by discordier** [comment]
I like the integration of the bundle, the configuration details might have to be discussed though.

**Comment by DanielSchwiperich** [comment]
Do I see this correct that this is already implemented in 4.3.7 and max security settings are in effect since there is no contao configuration for this?

https://github.com/contao/standard-edition/commit/89739deabd5ed59dc347b90e4c58695092a7e04b

**Comment by leofeyer** [comment]
Nope: `CorsBundle` !== `SecurityBundle` 😄

**Comment by DanielSchwiperich** [comment]
😳  whoops sorry

**Comment by leofeyer** [comment]
Implemented in bb69c02478e611ac0c9663aad9efe0a4a64c3c18 and contao/manager-bundle@57280b10173e87a90dddb78eac235b713d13d03a.

**Comment by xchs** [comment]
I wanted to change the `Referrer-Policy` header since the default value of `origin-when-cross-origin`  is not recommended. So I have added the following security configuration to the `app/config/config.yml` and cleared the cache:
```yaml
# app/config/config.yml

# Framework configuration
framework:
    session:
        cookie_secure: true
        cookie_httponly: true

# Security configuration
nelmio_security:
    clickjacking:
        paths:
            '^/.*': DENY
    content_type:
        nosniff: true
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
    xss_protection:
        enabled: true
        mode_block: true
    forced_ssl:
        hsts_max_age: 31536000
        hsts_subdomains: true
```
I would have expected that the `Referrer-Policy` header set to `no-referrer`, but I always get `Referrer-Policy: origin-when-cross-origin, no-referrer` instead.

**Comment by leofeyer** [comment]
What's the matter with `origin-when-cross-origin`?

**Comment by xchs** [comment]
https://securityheaders.io/?q=contao.org&hide=on&followRedirects=on
https://observatory.mozilla.org/analyze.html?host=contao.org

**Comment by xchs** [comment]
The problem is further: I can easily set all those security headers on a global scope by adding the respective directives to the web server configuration. However, if I do that all the headers set by the `NelmioSecurityBundle` appear then twice in the Response Header. I guess there is no easy way to disable the security features provided by the `NelmioSecurityBundle` (besides doing a `composer remove nelmio/security-bundle` in which I am unsure what impact this has on the application at all)?

**Comment by ausi** [comment]
> What's the matter with `origin-when-cross-origin`?

The difference between `origin-when-cross-origin` and `strict-origin-when-cross-origin` is that the strict version does not send any referrer if the source is on HTTPS and the target is on HTTP.

But the strict version is [not supported in all browsers](http://caniuse.com/#feat=referrer-policy) so we should provide a fallback I think:

```
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
```

[According to the specification](https://www.w3.org/TR/2017/CR-referrer-policy-20170126/#unknown-policy-values) the browser should use the last value from the list that it supports. We should test that though.

**Comment by xchs** [comment]
> According to the specification the browser should use the last value from the list that it supports. We should test that though.

This is already mentioned in the https://github.com/nelmio/NelmioSecurityBundle README:
```yaml
…
    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
…
```

https://github.com/nelmio/NelmioSecurityBundle#referrer-policy

**Comment by ausi** [comment]
But using `no-referrer` as the fallback will break things in Chrome, because AFAIK Contao relies on the referrer for some features.

**Comment by xchs** [comment]
> I would have expected that the Referrer-Policy header set to no-referrer, but I always get Referrer-Policy: origin-when-cross-origin, no-referrer instead.

Okay, [that](https://github.com/nelmio/NelmioSecurityBundle/blob/master/EventListener/ReferrerPolicyListener.php#L39) `implode()` seems to be the reason why this happens. Hmm…

**Comment by leofeyer** [comment]
So what do we do?

**Comment by xchs** [comment]
I think, @ausi's proposal should be fine:

> `Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin`
>
>According to the specification the browser should use the last value from the list that it supports. We should test that though.

```yaml
…
    referrer_policy:
        enabled: true
        policies:
            - 'origin-when-cross-origin'
            - 'strict-origin-when-cross-origin'
…
```
