### ISSUE TITLE
Unification of contao parameters

### ISSUE THREAD

**Issue by agoat** [contao/standard-edition#65]
Why do we have to set the `url_suffix` in the `config.yml` and the `prepend_locale` in the paramters.yml?
Both are related to the contao configuration.

In the config.yml the prepend_locale is taken from the parameter `%prepend_locale%` which is defined in the paramters.yml.
```yml
# Contao configuration
contao:
    prepend_locale: "%prepend_locale%"

```
I know the url_suffix is optional, but what if we generate this with the install tool like the `prepend_locale` parameter?

config.yml
```yml

# Contao configuration
contao:
    prepend_locale: "%prepend_locale%"
    url_suffix: "%url_suffix%"
```

parameters.yml
```yml
# This file is auto-generated during the composer install
parameters:
    secret: ...
    database_host: localhost
    database_port: 3306
    database_user: ...
    database_password: ...
    database_name: ...
    mailer_transport: mail
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_port: 25
    mailer_encryption: null
    prepend_locale: false
    url_suffix: 'html'
```

Btw the `url_suffix` parameter is not documented.
